### PR TITLE
feat: set server as authoritative

### PR DESCRIPTION
**Pull request by Trois-Six**
Hi!

The answers of the server are not seen as authoritative whereas they should. Because it's the goal of the project no?

Thx,

Pierre

### CODE REVIEW

**Comment by foxcpp** [comment]
The goal of the project is to stub out the system resolver - it is not meant to be an authoritative server. Is there any particular reason you need this?

**Comment by Trois-Six** [comment]
Yes, because in my project I am doing a manual recursive resolution of one DNS entry to not have to wait before the propagation a DNS zone modification. Since I am doing by myself the recursive resolution, I must know when I am speaking to the server that is authoritative for the DNS zone.

**Comment by foxcpp** [comment]
Okay, could you make it optional by adding an exported bool variable to Server object? You also probably want to unset RecursionAvailable since that's not what authoritative servers typically offer.

**Comment by Trois-Six** [comment]
ok! will do.

**Comment by Trois-Six** [comment]
Sorry, my IDE indented the code at the same time...

**Comment by foxcpp** [comment]
Thanks!

**Comment by Trois-Six** [comment]
I have just seen that I forgot to modify the README.

**Comment by foxcpp** [comment]
Fixed it.

**Pull request merged**
